### ISSUE TITLE
Essentials conflicts with PowerRanks

### ISSUE THREAD

**Issue by SimplyBrandon** [svenar-nl/PowerRanks#20] opened 2020-12-27 05:14 UTC
`[Server] Server thread/ERROR [com.earth2me.essentials.Essentials]: [Essentials] Permission System Error: SuperpermsHandler returned: null`

The permissions set by PowerRanks **1.9.3** are not being passed to the SuperpermsHandler and **therefore none of the permissions permitted by PowerRanks to individual ranks are making any changes**.

Provided .yml's:
PowerRanks config.yml: https://pastebin.com/T4s8eEuL
PowerRanks ranks.yml: https://pastebin.com/rPK0bk8j
Essentials config.yml: https://pastebin.com/tg15q1QG

Recommended to revert to 1.9.2 until patched.

**Comment by svenar-nl** [comment] 2020-12-27 11:52
Thanks for reporting this issue.

The error is caused by a negative array pop in PowerRanks
https://github.com/svenar-nl/PowerRanks/blob/f6a6653c2a16c7b6c69d1728b64a4b4cfba0bb00/PowerRanks/src/nl/svenar/PowerRanks/Data/PowerPermissibleBase.java#L61

This will be fixed in PowerRanks v1.9.4

**Comment by svenar-nl** [comment] 2020-12-27 23:00
Fixed in v1.9.4

**Closed by svenar-nl** 2020-12-27 23:00 UTC
